HR:
  PATH_MAIN: C:/Users/XXXX/Desktop/RANKING/HR/
  INGESTION:
    PATH_ING: DATA/
    FILENAME: Placement_Data_Full_Class.csv
    SEP: ','
  VIZ:
    PATH_VIZ: VIZ/
  MODEL:
    PATH_MODEL: MODEL/

CHURN:
  PATH_MAIN: C:/Users/XXXX/Desktop/RANKING/CHURN/
  INGESTION:
    PATH_ING: DATA/
    FILENAME: credit_card_churn.csv
    SEP: ','
  VIZ:
    PATH_VIZ: VIZ/
  MODEL:
    PATH_MODEL: MODEL/