RANDOM_FOREST:
  n_estimators:
    - 20
    - 30
    - 40
    - 50
  criterion:
    - gini
    - entropy
  max_depth:
    - 4
    - 5
    - 6
  min_samples_leaf:
    - 10
    - 15
    - 20
  max_features:
    - 5
    - 8
    - 10
  class_weight:
    - 'balanced'
    - 'balanced_subsample'