RANDOM_FOREST:
    criterion:
      - gini
      - entropy
    max_depth:
      - 5
      - 8
      - 10
      - 12
    min_samples_leaf:
      - 10
      - 15
      - 20
    max_features:
      - 10
      - 20
      - 30
      - 'sqrt'